### ISSUE TITLE
大哥你好，我这有补丁的一些难点

### ISSUE THREAD

**Issue by Jshu18** [Vetoyi/CN_Patch.Acting_Lessons#1]
你好大佬，我在github上下载不了这个补丁，也可能是我网络的问题，大佬可以在这补一个百度网盘的acting lessonsd的汉化补丁吗，谢谢了

**Comment by Vetoyi** [comment]
嗯...事实是我并没有上传这个补丁，这是为什么你下载不了。

**Comment by Vetoyi** [comment]
补丁已更新，请重新检查补丁说明并下载。
