### ISSUE TITLE
大佬上面的问题已经解决，但是我下载的这个文件怎么安装到游戏里

### ISSUE THREAD

**Issue by Jshu18** [Vetoyi/CN_Patch.Acting_Lessons#2]
我要怎么安装这个的汉化文件，他下载的是一个md文件

**Comment by Vetoyi** [comment]
你下载的其实这个GitHub库的文件，会包含补丁说明或图片之类的，但不含补丁，如果有则都是像其它补丁说明页那样直接写百度网盘多少、GitHub下载地址多少，这个游戏我之前汉化补丁做了一半然后一直没上传，现在这个GitHUb库是没有内容的

**Comment by Jshu18** [comment]
好的谢谢大佬，幸苦了，大佬我问一下，我们还有机会用到这个的汉化吗

**Comment by Vetoyi** [comment]
简短的说：答案是会，快的话我也许会在2月的某天发布。

实际上补丁的所有文本汉化均在半年前就早已完成，采用的依旧是大帝国汉化组的文本，一直没上是因为：
1. 小部分汉化即提示性文本尚未实装(如:选A选项后会提示XX喜欢你这么说/做)。
2. 我想重新校对所有剧情对话并完善翻译不佳的地方。
3. 而实际情况是我一想到上述目标的工作量后就直接摆烂了并拖更至今。

所以结论是，我会在之后更新这个补丁，因为已经拖了半年多而你既然碰巧又问了，索性有空就直接发了吧。但上述目标还是不会完成，并且我也依旧不会保证补丁后续更新。补丁目前效果可以做到解锁全成就、汉化全剧情台词，就单纯冲品味剧情而言，倒是足矣。

P.S. 另一点则是因为我早已通关并全成就该游戏，而我对已经品过全剧情的游戏没有太大更新动力。

**Comment by Vetoyi** [comment]
补丁已更新，请重新检查补丁说明并下载。

**Comment by owenluo1** [comment]
大佬牛B
